name: Build and Publish reptest

on:
  push:
    branches:
      - DEVELOPMENT_V0.7

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for hascoapi
        run: docker build -t TiagoMoreira2099/reptest:DEVELOPMENT_V0.7 .

      - name: Push Docker image to Docker Hub
        run: docker push TiagoMoreira2099/reptest:DEVELOPMENT_V0.7
