name: Update Packagist

on:
  push:
    branches:
      - main  # Modifique aqui caso queira acionar em outros branches

jobs:
  update-packagist:
    runs-on: ubuntu-latest
    steps:
    - name: Notify Packagist of update
      run: |
        curl -X POST https://packagist.org/api/update-package?username=tiagomoreira&apiToken=${{ secrets.PACKAGIST_TOKEN }} \
        -d '{"repository":{"url":"https://github.com/TiagoMoreira2099/reptest"}}'
